version: '3'
services:
  db:
    build:
      context: ./Image-Mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080

  react:
    depends_on:
      - db
      - app
    build:
      context: ./petclinic-web/web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

